### ISSUE TITLE
Warning of deprecated packages

### ISSUE THREAD

**Issue by elstamey** [phergie/phergie-irc-plugin-react-commandhelp#4]
I'm leaving this note here.  When I run composer for commandhelp, I see the following errors

`Package wyrihaximus/phergie-dns is abandoned, you should avoid using it. Use phergie/phergie-irc-plugin-dns instead.`

`Package wyrihaximus/phergie-http is abandoned, you should avoid using it. Use phergie/phergie-irc-plugin-http instead.`

I'm not positive about whether this is caused by commandhelp or another package dependency.  But I wanted to make a note of the issue here to check later.

**Comment by elazar** [comment]
Pretty sure this is specific to your dev environment and not to commandhelp in particular since it doesn't use these plugins or any that do. That said, we are aware of the package deprecations and it is something we're looking to address in the long term. Unfortunately, updating references to a package depended on by a lot of other packages is rather messy business. Thanks for the report though.
